title: 'Learn2 Site with Git Sync'
default_lang: en
author:
  name: 'John Appleseed'
  email: john@email.com
taxonomies: [category,tag,author]
metadata:
  description: 'Learn2 Site'
summary:
  size: 300
